globaljob/Models/Offre.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace globaljob.Models
{
    public class Offre
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        [Required]
        public DateTime DatePublication { get; set; }

        [DataType(DataType.Date)]
        [Required]
        public DateTime DateFin { get; set; }

        [DataType(DataType.MultilineText)]
        [Required]
        public string Description { get; set; }

        [DataType(DataType.Text)]
        [Required]
        public string Titre { get; set; }

        public List<Candidature> Candidature { get; set; }

        public string ApplicationUserId { get; set; }

        public ApplicationUser ApplicationUser { get; set; }
    }
}

globaljob/Controllers/CandidatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using globaljob.Data;
using globaljob.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Identity;

namespace globaljob.Controllers
{
    public class CandidatureController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<ApplicationUser> _userManager;
        public static int offreId;

        public CandidatureController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }

        // GET: Candidature
        public async Task<IActionResult> Index()
        {
            var candidatures = await _context.Candidature.ToListAsync();
            List<Candidature> candidaturesOffre = new();

            foreach (Candidature candidature in candidatures)
            {
                if (candidature.OffreId.Equals(offreId))
                {
                    candidaturesOffre.Add(candidature);
                }
            }

            return View(candidaturesOffre);
        }

        // GET: Candidature/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidature = await _context.Candidature
                .Include(c => c.Offre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (candidature == null)
            {
                return NotFound();
            }

            return View(candidature);
        }

        // GET: Candidature/Create
        public  IActionResult Create()
        {
            var user = _userManager.FindByIdAsync(_userManager.GetUserId(HttpContext.User)).Result;
            ViewData["FullName"] = user.FirstName + " " + user.LastName;
            ViewData["UserEmail"] = user.Email;
            ViewData["UserPhoneNumber"] = user.PhoneNumber;
            //if (id is not null)
            //{
            //    offreId = (int)id;
            //}

            // ViewData["offreId"] = offreId;

            return View();
        }

        // POST: Candidature/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Candidature candidature) //[Bind("Id,Name,Email,PhoneNumber,ResumeURL,OffreId")] 
        {
           candidature.OffreId = _context.Offre.Find(offreId).Id;
            if (ModelState.IsValid)
            {
                if (candidature.Resume != null)
                {
                    string folder = "resumes/";
                    candidature.ResumeURL = await UploadImage(folder, candidature.Resume);
                }
                _context.Add(candidature);
                await _context.SaveChangesAsync();
                TempData["AlertMessage"] = "Postulation enregistrée avec succès";
                return RedirectToAction(nameof(Create));
            }
            return View();
        }

        // GET: Candidature/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidature = await _context.Candidature.FindAsync(id);
            if (candidature == null)
            {
                return NotFound();
            }
            ViewData["OffreId"] = new SelectList(_context.Offre, "Id", "Description", candidature.OffreId);
            return View(candidature);
        }

        // POST: Candidature/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,PhoneNumber,ResumeURL,OffreId")] Candidature candidature)
        {
            if (id != candidature.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(candidature);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CandidatureExists(candidature.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OffreId"] = new SelectList(_context.Offre, "Id", "Description", candidature.OffreId);
            return View(candidature);
        }

        // GET: Candidature/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var candidature = await _context.Candidature
                .Include(c => c.Offre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (candidature == null)
            {
                return NotFound();
            }

            return View(candidature);
        }

        // POST: Candidature/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var candidature = await _context.Candidature.FindAsync(id);
            _context.Candidature.Remove(candidature);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CandidatureExists(int id)
        {
            return _context.Candidature.Any(e => e.Id == id);
        }

        private async Task<string> UploadImage(string folderPath, IFormFile file)
        {
            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;

            string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folderPath);

            await file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return "/" + folderPath;
        }

    }
}

globaljob/Controllers/OffreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using globaljob.Data;
using globaljob.Models;
using Microsoft.AspNetCore.Identity;

namespace globaljob.Controllers
{
    public class OffreController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public OffreController(ApplicationDbContext context,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Offre
        public async Task<IActionResult> Index()
        {
            var offres = await _context.Offre.ToListAsync();
            List<Offre> offresRecruteur = new();
            var UserId = _userManager.GetUserId(HttpContext.User);

            foreach (Offre offre in offres)
            {
                if (offre.ApplicationUserId is not null && offre.ApplicationUserId.Equals(UserId))
                {
                    offresRecruteur.Add(offre);
                }

            }

            return View(offresRecruteur);
        }

        public async Task<IActionResult> Consulter_Offres()
        {
            return View(await _context.Offre.ToListAsync());
        }

        public async Task<IActionResult> Details_Offre(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offre = await _context.Offre
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offre == null)
            {
                return NotFound();
            }

            return View(offre);
        }
        // GET: Offre/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offre = await _context.Offre
                .Include(o => o.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offre == null)
            {
                return NotFound();
            }

            return View(offre);
        }

        // GET: Offre/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Offre/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DatePublication,DateFin,Description,Titre")] Offre offre)
        {
            offre.ApplicationUserId = _userManager.GetUserId(HttpContext.User);
            if (ModelState.IsValid)
            {
                _context.Add(offre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(offre);
        }

        // GET: Offre/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offre = await _context.Offre.FindAsync(id);
            if (offre == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", offre.ApplicationUserId);
            return View(offre);
        }

        // POST: Offre/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DatePublication,DateFin,Description,Titre")] Offre offre)
        {
            offre.ApplicationUserId = _userManager.GetUserId(HttpContext.User);
            if (id != offre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(offre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OffreExists(offre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", offre.ApplicationUserId);
            return View(offre);
        }

        // GET: Offre/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var offre = await _context.Offre
                .Include(o => o.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (offre == null)
            {
                return NotFound();
            }

            return View(offre);
        }

        // POST: Offre/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var offre = await _context.Offre.FindAsync(id);
            var candidature = await _context.Candidature
                .Include(c => c.Offre)
                .FirstOrDefaultAsync(m => m.OffreId == id);

            _context.Offre.Remove(offre);

            if (candidature is not null)
            {
                _context.Candidature.Remove(candidature);
            }
                
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OffreExists(int id)
        {
            return _context.Offre.Any(e => e.Id == id);
        }
    }
}

globaljob/Views/Offre/Consulter_Offres.cshtml
@model IEnumerable<globaljob.Models.Offre>

@{
    ViewData["Title"] = "Consulter_Offres";
}
<style>
.table{color:white;}
h1{color:white;}
</style>
<h1>Consulter_Offres</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DatePublication)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateFin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titre)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DatePublication)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateFin)
            </td>
            <td max>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td>
                <a asp-action="Details_Offre" asp-route-id="@item.Id" class="btn btn-primary">Details</a>
            </td>
        </tr>
}
    </tbody>
</table>

<script type="text/javascript">
    
</script>

globaljob/Views/Offre/Create.cshtml
@model globaljob.Models.Offre

@{
    ViewData["Title"] = "Create";
}
<style>
.row{color:white;}
h1{color:white;}
h4{color:white;}
</style>
<h1>Create</h1>

<h4>Offre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titre" class="control-label"></label>
                <input asp-for="Titre" class="form-control" />
                <span asp-validation-for="Titre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePublication" class="control-label"></label>
                <input asp-for="DatePublication" class="form-control" id="datePublicationCreate" />
                <span asp-validation-for="DatePublication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFin" class="control-label"></label>
                <input asp-for="DateFin" class="form-control" />
                <span asp-validation-for="DateFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/offre.js"></script>
}

globaljob/Views/Offre/Delete.cshtml
@model globaljob.Models.Offre

@{
    ViewData["Title"] = "Delete";
}
<style>
.row{color:white;}
h1{color:white;}
h3{color:white;}
h4{color:white;}


</style>
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Offre</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DatePublication)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DatePublication)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

globaljob/Views/Offre/Details.cshtml
@model globaljob.Models.Offre

@{
    ViewData["Title"] = "Details";
    globaljob.Controllers.CandidatureController.offreId = Model.Id;
}
<style>
.row{color:white;}
h1{color:white;}
h4{color:white;}
a{color:white;}
a:hover{color:white;}
</style>
<h1>Details</h1>

<div>
    <h4>Offre</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DatePublication)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DatePublication)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary mr-2">Edit</a>
    <a asp-controller="Candidature" asp-action="Index"  class="btn btn-warning">Consulter Candidatures</a>
</div>

globaljob/Views/Offre/Details_Offre.cshtml
@model globaljob.Models.Offre
@{
    ViewData["Title"] = "Details_Offre";
    globaljob.Controllers.CandidatureController.offreId = Model.Id;
}
<style>
.row{color:white;}
h1{color:white;}
h4{color:white;}
a{color:white;}
a:hover{color:white;}
</style>
<h1>Details_Offre</h1>

<div>
    <h4>Offre</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DatePublication)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DatePublication)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Consulter_Offres" class="btn btn-primary">Retouner</a>
    <a class="btn btn-warning" asp-controller="Candidature" asp-action="Create">Postuler</a> @*asp-route-id="@Model.Id"*@
</div>

globaljob/Views/Offre/Edit.cshtml
@model globaljob.Models.Offre

@{
    ViewData["Title"] = "Edit";
}
<style>
.row{color:white;}
h1{color:white;}
h4{color:white;}
a{color:white;}
a:hover{color:white;}
</style>
<h1>Edit</h1>

<h4>Offre</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titre" class="control-label"></label>
                <input asp-for="Titre" class="form-control" />
                <span asp-validation-for="Titre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePublication" class="control-label"></label>
                <input asp-for="DatePublication" class="form-control" />
                <span asp-validation-for="DatePublication" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFin" class="control-label"></label>
                <input asp-for="DateFin" class="form-control" />
                <span asp-validation-for="DateFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

globaljob/Views/Offre/Index.cshtml
@model IEnumerable<globaljob.Models.Offre>

@{
    ViewData["Title"] = "Index";
}
<style>
.table{color:white;}
h1{color:white;}

</style>
<h1 class="text-center">Gérer les offres</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th class="text-center" style="border-top: none;">
                @Html.DisplayNameFor(model => model.DatePublication)
            </th>
            <th class="text-center" style="border-top: none;">
                @Html.DisplayNameFor(model => model.DateFin)
            </th>
            <th class="text-center" style="border-top: none;">
                @Html.DisplayNameFor(model => model.Titre)
            </th>
            <th class="text-center" style="border-top: none;">
                Gestion
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.DatePublication)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.DateFin)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td class="text-center">
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">Lire Détails</a>

            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>